name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Build
    uses: ashutoshvarma/action-cmake-build@master
    with:
      build-dir: ${{ runner.workspace }}/build
      build-type: Release
